// const storecheck = require('./Linked List/deletion')
// const insert = require('./Linked List/insert')
// const basicoperations = require('./Linked List/basicoperations')
const DLL = require('./Linked List/DLL')
const bsicOperationInDLL = require('./Linked List/bsicOperationInDLL')

// const bubblesort = require('./sorting/bubblesort')
// const mergeSort = require('./sorting/mergeSort')
// console.log("check")
console.log("Ayyapa")